source = ~/.config/hypr/background.conf
source = ~/.config/hypr/programs.conf
source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/appearance.conf
source = ~/.config/hypr/env.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/keybinds.conf
source = ~/.config/hypr/window-rules.conf
source = ~/.config/hypr/xwayland-fix.conf
# source = ~/.config/hypr/debug.conf # Just for debugging

# source = ~/.config/hypr/plugins/hyprexpo.conf
source = ~/.config/hypr/plugins/hyprspace.conf

# >>> jcode launch hotkeys (managed) >>>
# jcode: home
bind = SUPER, semicolon, exec, '/home/phenchua/.jcode/hotkey/launch_jcode_0_cmd_semicolon.sh'
# jcode: last project
bind = SUPER, apostrophe, exec, '/home/phenchua/.jcode/hotkey/launch_jcode_1_cmd_quote.sh'
# jcode: self-dev
bind = SUPER SHIFT, apostrophe, exec, '/home/phenchua/.jcode/hotkey/launch_jcode_2_cmd_shift_quote.sh'
# <<< jcode launch hotkeys (managed) <<<
