source = ~/.config/hypr/background.conf
source = ~/.config/hypr/programs.conf
source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/appearance.conf
source = ~/.config/hypr/env.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/keybinds.conf
source = ~/.config/hypr/window-rules.conf
source = ~/.config/hypr/xwayland-fix.conf
# source = ~/.config/hypr/debug.conf # Just for debugging

# source = ~/.config/hypr/plugins/hyprexpo.conf
source = ~/.config/hypr/plugins/hyprspace.conf
